name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"

permissions:
  contents: write

env:
  QT_OUTPUT_DIR_NAME: qt_output
  QT_SRC_DIR_NAME: qt_src
  QT_CFG_ARGS: -opensource -release -static -nomake examples -nomake tests -skip qt3d -skip qttranslations -skip qt5compat -skip qtactiveqt -skip qtcharts -skip qtcoap -skip qtconnectivity -skip qtdatavis3d -skip qtdeclarative -skip qtdoc -skip qthttpserver -skip qtlanguageserver -skip qtlottie -skip qtmqtt -skip qtmultimedia -skip qtnetworkauth -skip qtopcua -skip qtpositioning -skip qtquick3d -skip qtquick3dphysics -skip qtquicktimeline -skip qtremoteobjects -skip qtscxml -skip qtsensors -skip qtserialbus -skip qtserialport -skip qtshadertools -skip qtspeech -skip qtsvg -skip qttools -skip qtwebsockets

jobs:
  build-win64:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        version: [6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: git make

      # set environment variables
      - run: echo "$PWD"
      - run: |
          echo "QT_SRC_DIR=$PWD/${{ env.QT_SRC_DIR_NAME }}">>$GITHUB_ENV
          echo "QT_OUTPUT_DIR=$PWD/${{ env.QT_OUTPUT_DIR_NAME }}">>$GITHUB_ENV

          echo "ASSET=qt-${{ matrix.version }}-${{ matrix.os }}.tar.gz">>$GITHUB_ENV
          echo 'C:/ProgramData/Chocolatey/bin' $GITHUB_PATH
          echo 'C:/Strawberry/perl/bin' $GITHUB_PATH
          echo 'C:/hostedtoolcache/windows/Ruby/2.5.9/x64/bin' $GITHUB_PATH
          echo 'C:/hostedtoolcache/windows/Python/3.7.9/x64/bin' $GITHUB_PATH
          echo 'C:/Program Files/CMake/bin' $GITHUB_PATH

      - run: git clone https://code.qt.io/qt/qt5.git -b v${{ matrix.version }} ${{ env.QT_SRC_DIR }}

      - run: |
          cd ${{ env.QT_SRC_DIR }}
          perl init-repository -f --module-subset=qtbase

      - run: |
          cd ${{ env.QT_SRC_DIR }}
          ./configure -prefix ${{ env.QT_OUTPUT_DIR }} ${{ env.QT_CFG_ARGS }} -platform win32-g++

      - run: |
          cd ${{ env.QT_SRC_DIR }}
          ninja -j6 && ninja install

      - run: |
          cd ${{ env.QT_OUTPUT_DIR }}/..
          tar -zcvf ${{ env.ASSET }} ${{ env.QT_OUTPUT_DIR_NAME }}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ASSET }}
          generate_release_notes: true
